"""add last_error_code to domains

Revision ID: 081b8d4b1c4f
Revises: 
Create Date: 2025-09-23 11:05:22.186856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081b8d4b1c4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('last_error_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'last_error_code')
    # ### end Alembic commands ###
