"""add users table

Revision ID: 8d4f41b7ec46
Revises: 081b8d4b1c4f
Create Date: 2025-09-23 14:23:02.132485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4f41b7ec46'
down_revision = '081b8d4b1c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
